---
# External drives attached to the Proxmox host.
external_disks:
  - name: "ssd-backup"
    by_id: "usb-BIueendIess_BIueendIess_0BIueendIes6-0:0-part1"
    opts: "defaults"
    dir_mode: "0777"
    assert_dirs:
      - "PlexMedia"
    create_dirs:
      - "PlexConfig"