# AdGuard Home
adguard_http_address: "192.168.1.101:80"
adguard_docker_reverse_proxy_ip: "192.168.1.102"

adguard_tls_server_name: "adguard.internal"
adguard_cert_directory: /opt/AdGuardHome/certs
adguard_dns_ipv6: true
adguard_admin_username: "{{ admin_username }}"
adguard_alt_names:
  - "*.docker.internal"
  - "docker.internal"
  - "*.internal"
  - "internal"
  - "*.k8s.internal"
  - "k8s.internal"
  - "*.k3s.internal"
  - "k3s.internal"
adguard_alt_ips:
  - "{{ adguard_http_address.split(':')[0] }}"
adguard_dns_rewrites:
  - domain: "adguard.internal"
    answer: "{{ adguard_http_address.split(':')[0] }}"
    enabled: true
  - domain: "plex.internal"
    answer: "192.168.1.103"
    enabled: true
  - domain: "*.docker.internal"
    answer: "{{ adguard_docker_reverse_proxy_ip }}"
    enabled: true
  - domain: "*.k3s.internal"
    answer: "192.168.1.104"
    enabled: true
