# Disk configuration
docker_disk_id: "/dev/disk/by-id/virtio-DOCKER-DATA"
docker_mount_point: "/mnt/docker-data"

# Application paths
docker_engine_root: "{{ docker_mount_point }}/docker-engine"
containerd_root: "{{ docker_mount_point }}/containerd-data"

# Docker Daemon Options
docker_daemon_options:
  data-root: "{{ docker_engine_root }}"
  log-driver: "json-file"
  log-opts:
    max-size: "10m"
    max-file: "3"

# Docker Cleanup Settings
# Sunday at 3am
docker_cleanup_cron_minute: "0"
docker_cleanup_cron_hour: "1"
docker_cleanup_cron_weekday: "0"
docker_cleanup_command: "/usr/bin/docker system prune -a -f --volumes"
