# Disk configuration
docker_disk_id: "/dev/disk/by-id/virtio-DOCKER-DATA"
docker_mount_point: "/mnt/docker-data"

# Application paths
docker_engine_root: "{{ docker_mount_point }}/docker-engine"
containerd_root: "{{ docker_mount_point }}/containerd-data"

# User settings
docker_target_user: "skoltun"

# Docker Daemon Options
docker_daemon_options:
  data-root: "{{ docker_engine_root }}"
  log-driver: "json-file"
  log-opts:
    max-size: "10m"
    max-file: "3"