# Docker Configuration
docker:
  user: "{{ admin_username }}"
  disk_id: "/dev/disk/by-id/virtio-DOCKER-DATA"
  mount_point: "/mnt/docker-data"
  engine_root: "{{ docker.mount_point }}/docker-engine"
  containerd_root: "{{ docker.mount_point }}/containerd-data"
  daemon_options:
    data-root: "{{ docker.engine_root }}"
    log-driver: "json-file"
    log-opts:
      max-size: "10m"
      max-file: "3"
  cleanup:
    minute: "0"
    hour: "1"
    weekday: "0"
    command: "/usr/bin/docker system prune -a -f --volumes"