# AdGuard Home Configuration
adguard:
  install_script_url: https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh
  service_name: AdGuardHome
  http_address: "{{ container_ip }}:80"
  docker_reverse_proxy_ip: "{{ hostvars['docker-host'].ansible_host }}"
  dns_ipv6: true
  admin_username: "{{ admin_username }}"
  dns_rewrites:
    "adguard.homelab": "{{ container_ip }}"
    "plex.homelab": "{{ hostvars['plex-host'].container_ip }}"
    "*.docker.homelab": "{{ hostvars['docker-host'].ansible_host }}"
    "*.k3s.skoltun.dev": "{{ hostvars['k3s-node'].ansible_host }}"