# Plex Media Server Configuration
plex:
  package_name: "plexmediaserver"

  mounts:
    media:
      id: "mp0"
      host_path: "/mnt/pve/ssd-backup/PlexMedia"
      container_path: "/PlexMedia"
    config:
      id: "mp1"
      host_path: "/mnt/pve/ssd-backup/PlexConfig"
      container_path: "/plex-config"

  service:
    override_dir: "/etc/systemd/system/plexmediaserver.service.d"
    override_file: "/etc/systemd/system/plexmediaserver.service.d/override.conf"

  apt:
    repo_file: "/etc/apt/sources.list.d/plexmediaserver.list"
    repo: "deb [trusted=yes] https://downloads.plex.tv/repo/deb public main"