---
- name: AdGuard Home installation
  hosts: role_adguard
  gather_facts: false

  tasks:
    - name: Ensure configuration directory exists
      ansible.builtin.file:
        path: /opt/AdGuardHome
        state: directory
        mode: '0700'

    - name: Check if AdGuard Home is running
      ansible.builtin.systemd:
        name: AdGuardHome
      register: adguard_service

    - name: Download AdGuard Home install script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh
        dest: /tmp/install_adguard.sh
        mode: "0755"
      when: adguard_service.status.ActiveState != "active"

    - name: Install AdGuard Home
      ansible.builtin.command: /tmp/install_adguard.sh -r
      when: adguard_service.status.ActiveState != "active"

    - name: Remove installation script
      ansible.builtin.file:
        path: /tmp/install_adguard.sh
        state: absent
      when: adguard_service.status.ActiveState != "active"

    - name: Deploy AdGuardHome.yaml
      ansible.builtin.template:
        src: "{{ playbook_dir }}/config/AdGuardHome.yml.j2"
        dest: /opt/AdGuardHome/AdGuardHome.yaml
        mode: '0644'
      notify: Restart AdGuard Home

    - name: Enable and start AdGuard Home service
      ansible.builtin.systemd:
        name: AdGuardHome
        state: started
        enabled: true

  handlers:
    - name: Restart AdGuard Home
      ansible.builtin.systemd:
        name: AdGuardHome
        state: restarted
