---
- name: Ensure cron is installed
  ansible.builtin.package:
    name: cron
    state: present

- name: Ensure cron service is running
  ansible.builtin.systemd:
    name: cron
    state: started
    enabled: true

- name: Add docker prune to crontab
  ansible.builtin.cron:
    name: "Docker system prune"
    minute: "{{ docker.cleanup.minute }}"
    hour: "{{ docker.cleanup.hour }}"
    weekday: "{{ docker.cleanup.weekday }}"
    job: "{{ docker.cleanup.command }}"
    user: "root"