---
all:
  vars:
    ansible_private_key_file: ~/.ssh/id_ed25519

  children:
    pve:
      hosts:
        pve-host:
          ansible_host: 192.168.1.100
          ansible_user: root

    lxc_containers:
      vars:
        ansible_host: 192.168.1.100
        ansible_connection: community.proxmox.proxmox_pct_remote
        ansible_host_key_checking: false
      children:
        role_adguard:
          hosts:
            adguard-host:
              proxmox_vmid: 101
              container_ip: 192.168.1.101
              ansible_user: root

        role_plex:
          hosts:
            plex-host:
              proxmox_vmid: 103
              container_ip: 192.168.1.103
              ansible_user: root

    role_docker:
      hosts:
        docker-host:
          ansible_host: 192.168.1.102
          ansible_user: skoltun

    role_k3s:
      hosts:
        k3s-node:
          ansible_host: 192.168.1.104
          ansible_user: skoltun